import type { ShipmentOverviewRow } from './shipment-overview-query.repository.js';

export type MarketShipmentView = Partial<ShipmentOverviewRow> & Pick<ShipmentOverviewRow, 'id' | 'status' | 'createdAt'>;

export function projectMarketShipment(shipment: ShipmentOverviewRow, includeRouteCost = false): MarketShipmentView {
  return {
    id: shipment.id,
    createdAt: shipment.createdAt,
    entryAt: shipment.entryAt,
    customerName: shipment.customerName,
    customerId: shipment.customerId,
    customerCode: shipment.customerCode,
    salesperson: shipment.salesperson,
    customerOrderNo: shipment.customerOrderNo,
    outboundOrderNo: shipment.outboundOrderNo,
    systemOrderNo: shipment.systemOrderNo,
    transferNo: shipment.transferNo,
    subOrderNo: shipment.subOrderNo,
    outboundAt: shipment.outboundAt,
    productName: shipment.productName,
    declarationRequired: shipment.declarationRequired,
    sensitive: shipment.sensitive,
    cargoType: shipment.cargoType,
    volumeCbm: shipment.volumeCbm,
    actualWeightKg: shipment.actualWeightKg,
    weightKg: shipment.weightKg,
    cargoDataSource: shipment.cargoDataSource,
    chargeWeightOverridden: shipment.chargeWeightOverridden,
    businessReviewedAt: shipment.businessReviewedAt,
    reviewedAt: shipment.reviewedAt,
    etaAt: shipment.etaAt,
    etdAt: shipment.etdAt,
    businessType: shipment.businessType,
    packageType: shipment.packageType,
    destinationCountry: shipment.destinationCountry,
    carrier: shipment.carrier,
    packageCount: shipment.packageCount,
    receivableWeightKg: shipment.receivableWeightKg,
    latestTracking: shipment.latestTracking,
    latestTrackingUpdatedAt: shipment.latestTrackingUpdatedAt,
    trackingStaleDays: shipment.trackingStaleDays,
    isRemoteArea: shipment.isRemoteArea,
    status: shipment.status,
    channelId: shipment.channelId,
    channelName: shipment.channelName,
    agentId: shipment.agentId,
    agentName: shipment.agentName,
    routedAt: shipment.routedAt,
    routeReturnedAt: shipment.routeReturnedAt,
    routeAgentChannelName: shipment.routeAgentChannelName,
    ...(includeRouteCost ? {
      routeChargeWeightKg: shipment.routeChargeWeightKg,
      routeUnitPrice: shipment.routeUnitPrice,
      routeOtherFee: shipment.routeOtherFee,
      routeCostTotal: shipment.routeCostTotal,
      routeCurrency: shipment.routeCurrency,
      routeCostSummary: shipment.routeCostSummary
    } : {}),
    agentReplacementCount: shipment.agentReplacementCount,
    agentChangeRequest: shipment.agentChangeRequest,
    warehouseOutboundRemark: shipment.warehouseOutboundRemark,
    shippingMarkRequired: shipment.shippingMarkRequired,
    hasProblemTicket: shipment.hasProblemTicket,
    site: shipment.site
  };
}

export function projectMarketRoutingReportShipment(shipment: ShipmentOverviewRow): MarketShipmentView {
  const projected = projectMarketShipment(shipment, true);
  return {
    id: projected.id,
    createdAt: projected.createdAt,
    customerName: projected.customerName,
    customerCode: projected.customerCode,
    salesperson: projected.salesperson,
    customerOrderNo: '',
    systemOrderNo: projected.systemOrderNo,
    transferNo: projected.transferNo,
    outboundAt: projected.outboundAt,
    declarationRequired: projected.declarationRequired,
    sensitive: projected.sensitive,
    businessType: projected.businessType,
    packageType: projected.packageType,
    destinationCountry: projected.destinationCountry,
    carrier: projected.carrier,
    packageCount: projected.packageCount,
    receivableWeightKg: projected.receivableWeightKg,
    latestTracking: '',
    trackingStaleDays: 0,
    isRemoteArea: false,
    status: projected.status,
    channelName: projected.channelName,
    agentName: projected.agentName,
    routedAt: projected.routedAt,
    routeReturnedAt: projected.routeReturnedAt,
    routeAgentChannelName: projected.routeAgentChannelName,
    routeChargeWeightKg: projected.routeChargeWeightKg,
    routeUnitPrice: projected.routeUnitPrice,
    routeOtherFee: projected.routeOtherFee,
    routeCostTotal: projected.routeCostTotal,
    routeCurrency: projected.routeCurrency,
    routeCostSummary: projected.routeCostSummary,
    hasProblemTicket: false,
    site: projected.site
  };
}
