ALTER TYPE "ShipmentStatus" ADD VALUE IF NOT EXISTS 'OUTBOUNDED';
ALTER TYPE "ShipmentStatus" ADD VALUE IF NOT EXISTS 'WAITING_DEPARTURE';
ALTER TYPE "ShipmentStatus" ADD VALUE IF NOT EXISTS 'DEPARTED';
ALTER TYPE "ShipmentStatus" ADD VALUE IF NOT EXISTS 'ARRIVED_PORT';
ALTER TYPE "ShipmentStatus" ADD VALUE IF NOT EXISTS 'DELIVERING';
ALTER TYPE "ShipmentStatus" ADD VALUE IF NOT EXISTS 'REVIEW_REJECTED';

ALTER TABLE "Shipment" ADD COLUMN IF NOT EXISTS "etaAt" TIMESTAMP(3);
ALTER TABLE "Shipment" ADD COLUMN IF NOT EXISTS "etdAt" TIMESTAMP(3);
