import type { BusinessType, Shipment } from '@siyuan/shared';

export const businessTabs: Array<{ key: BusinessType; label: string; count: number }> = [
  { key: 'EXPRESS', label: '快递', count: 66 },
  { key: 'SMALL_PACKET', label: '小包', count: 24 },
  { key: 'DEDICATED_LINE', label: '专线', count: 327 }
];

export const shipments: Shipment[] = [
  {
    id: 'SYGJ06059409051',
    createdAt: '2026-06-05 15:37',
    customerName: '9409-Daloday',
    customerOrderNo: 'DAL-0605-AU',
    systemOrderNo: 'SYGJ06059409051',
    businessType: 'EXPRESS',
    packageType: 'WPX',
    destinationCountry: '澳大利亚',
    carrier: 'FEDEX',
    packageCount: 4,
    receivableWeightKg: 56,
    agentWeightKg: 56,
    latestTracking: '收货扫描',
    trackingStaleDays: 1,
    isRemoteArea: false,
    status: 'WAITING_SORT',
    channelName: 'FEDEX AU 促销',
    agentName: '远东',
    hasProblemTicket: false
  },
  {
    id: 'SYGJ06051491040',
    createdAt: '2026-06-05 10:30',
    customerName: '1491-Jennifer Castillo',
    customerOrderNo: 'PE-1491-0605',
    systemOrderNo: 'SYGJ06051491040',
    businessType: 'EXPRESS',
    packageType: 'WPX',
    destinationCountry: '秘鲁',
    carrier: 'DHL',
    packageCount: 3,
    receivableWeightKg: 51,
    agentWeightKg: 51,
    latestTracking: '收货扫描',
    trackingStaleDays: 1,
    isRemoteArea: true,
    status: 'WAITING_SORT',
    channelName: 'HKD03 美洲代理价',
    agentName: '宇环',
    hasProblemTicket: false
  },
  {
    id: 'SYGJ05291344165',
    createdAt: '2026-05-27 16:58',
    customerName: '1344-TILL',
    customerOrderNo: 'TILL-0529',
    systemOrderNo: 'SYGJ05291344165',
    transferNo: '9064656160',
    businessType: 'EXPRESS',
    packageType: 'WPX',
    destinationCountry: '未知',
    carrier: 'DHL',
    packageCount: 5,
    receivableWeightKg: 77,
    agentWeightKg: 76,
    latestTracking: '离开扫描',
    trackingStaleDays: 9,
    isRemoteArea: false,
    status: 'WAITING_ONLINE',
    channelName: 'HKD01 代理价',
    agentName: '宇环',
    hasProblemTicket: true
  },
  {
    id: 'SYGJ05199509002',
    createdAt: '2026-05-19 18:56',
    customerName: '9509-Cam&Clae',
    customerOrderNo: 'OPEN-0519',
    systemOrderNo: 'SYGJ05199509002',
    businessType: 'EXPRESS',
    packageType: 'WPX',
    destinationCountry: '澳大利亚',
    carrier: 'FEDEX',
    packageCount: 1,
    receivableWeightKg: 49,
    agentWeightKg: 49,
    latestTracking: '离开扫描',
    trackingStaleDays: 6,
    isRemoteArea: true,
    status: 'WAITING_ONLINE',
    channelName: '越南原飞航',
    agentName: '越南原飞航',
    hasProblemTicket: false
  },
  {
    id: 'SYGJ04059409034',
    createdAt: '2026-04-25 11:47',
    customerName: '9409-Daloday',
    customerOrderNo: 'RETURN-0405',
    systemOrderNo: 'SYGJ04059409034',
    businessType: 'EXPRESS',
    packageType: 'WPX',
    destinationCountry: '澳大利亚',
    carrier: 'DHL',
    packageCount: 1,
    receivableWeightKg: 13,
    agentWeightKg: 12.5,
    latestTracking: '客户退件：不出',
    trackingStaleDays: 2,
    isRemoteArea: false,
    status: 'WAITING_RETURN',
    channelName: 'HKD11',
    agentName: '宇环',
    hasProblemTicket: true
  },
  {
    id: 'SYGJ04021344154',
    createdAt: '2026-04-02 09:23',
    customerName: '1344-TILL',
    customerOrderNo: 'DE-0402',
    systemOrderNo: 'SYGJ04021344154',
    transferNo: '1401428641',
    businessType: 'EXPRESS',
    packageType: 'WPX',
    destinationCountry: '德国',
    carrier: 'DHL',
    packageCount: 1,
    receivableWeightKg: 8,
    agentWeightKg: 7.5,
    latestTracking: '已签收',
    trackingStaleDays: 0,
    isRemoteArea: false,
    status: 'SIGNED',
    channelName: 'HKD01',
    agentName: '宇环',
    hasProblemTicket: false
  },
  {
    id: 'SYXB0606US001',
    createdAt: '2026-06-06 08:42',
    customerName: 'A100-北美电商',
    customerOrderNo: 'SP-US-0606',
    systemOrderNo: 'SYXB0606US001',
    businessType: 'SMALL_PACKET',
    packageType: 'PAK',
    destinationCountry: '美国',
    carrier: 'USPS',
    packageCount: 8,
    receivableWeightKg: 12.4,
    agentWeightKg: 12,
    latestTracking: '已预报',
    trackingStaleDays: 0,
    isRemoteArea: false,
    status: 'DECLARED',
    channelName: 'USPS 小包线',
    agentName: '蓝玛特',
    hasProblemTicket: false
  },
  {
    id: 'SYZX0606UK001',
    createdAt: '2026-06-06 09:03',
    customerName: 'B220-FBA 卖家',
    customerOrderNo: 'FBA-UK-0606',
    systemOrderNo: 'SYZX0606UK001',
    businessType: 'DEDICATED_LINE',
    packageType: 'WPX',
    destinationCountry: '英国',
    carrier: '专线',
    packageCount: 16,
    receivableWeightKg: 282,
    agentWeightKg: 282,
    latestTracking: '待排货',
    trackingStaleDays: 0,
    isRemoteArea: false,
    status: 'WAITING_SORT',
    channelName: '英国 FBA 空派',
    agentName: '中飞',
    hasProblemTicket: false
  }
];
