import type { BusinessType, Shipment } from '@siyuan/shared';

export const businessTabs: Array<{ key: BusinessType; label: string; count: number }> = [
  { key: 'EXPRESS', label: '快递', count: 66 },
  { key: 'SMALL_PACKET', label: '小包', count: 24 },
  { key: 'DEDICATED_LINE', label: '专线', count: 327 }
];

export const shipments: Shipment[] = [
  {
    id: 'SYGJ06059409051',
    createdAt: '2026-06-05 15:37',
    customerName: '9409-Daloday',
    customerOrderNo: 'DAL-0605-AU',
    systemOrderNo: 'SYGJ06059409051',
    businessType: 'EXPRESS',
    packageType: 'WPX',
    destinationCountry: '澳大利亚',
    carrier: 'FEDEX',
    packageCount: 4,
    receivableWeightKg: 56,
    agentWeightKg: 56,
    latestTracking: '收货扫描',
    trackingStaleDays: 1,
    isRemoteArea: false,
    status: 'WAITING_SORT',
    channelName: 'FEDEX AU 促销',
    agentName: '远东',
    hasProblemTicket: false
  },
  {
    id: 'SYGJ06051491040',
    createdAt: '2026-06-05 10:30',
    customerName: '1491-Jennifer Castillo',
    customerOrderNo: 'PE-1491-0605',
    systemOrderNo: 'SYGJ06051491040',
    businessType: 'EXPRESS',
    packageType: 'WPX',
    destinationCountry: '秘鲁',
    carrier: 'DHL',
    packageCount: 3,
    receivableWeightKg: 51,
    agentWeightKg: 51,
    latestTracking: '收货扫描',
    trackingStaleDays: 1,
    isRemoteArea: true,
    status: 'WAITING_SORT',
    channelName: 'HKD03 美洲代理价',
    agentName: '宇环',
    hasProblemTicket: false
  },
  {
    id: 'SYGJ05291344165',
    createdAt: '2026-05-27 16:58',
    customerName: '1344-TILL',
    customerOrderNo: 'TILL-0529',
    systemOrderNo: 'SYGJ05291344165',
    transferNo: '9064656160',
    businessType: 'EXPRESS',
    packageType: 'WPX',
    destinationCountry: '未知',
    carrier: 'DHL',
    packageCount: 5,
    receivableWeightKg: 77,
    agentWeightKg: 76,
    latestTracking: '离开扫描',
    trackingStaleDays: 9,
    isRemoteArea: false,
    status: 'WAITING_ONLINE',
    channelName: 'HKD01 代理价',
    agentName: '宇环',
    hasProblemTicket: true
  },
  {
    id: 'SYGJ05199509002',
    createdAt: '2026-05-19 18:56',
    customerName: '9509-Cam&Clae',
    customerOrderNo: 'OPEN-0519',
    systemOrderNo: 'SYGJ05199509002',
    businessType: 'EXPRESS',
    packageType: 'WPX',
    destinationCountry: '澳大利亚',
    carrier: 'FEDEX',
    packageCount: 1,
    receivableWeightKg: 49,
    agentWeightKg: 49,
    latestTracking: '离开扫描',
    trackingStaleDays: 6,
    isRemoteArea: true,
    status: 'WAITING_ONLINE',
    channelName: '越南原飞航',
    agentName: '越南原飞航',
    hasProblemTicket: false
  },
  {
    id: 'SYGJ04059409034',
    createdAt: '2026-04-25 11:47',
    customerName: '9409-Daloday',
    customerOrderNo: 'RETURN-0405',
    systemOrderNo: 'SYGJ04059409034',
    businessType: 'EXPRESS',
    packageType: 'WPX',
    destinationCountry: '澳大利亚',
    carrier: 'DHL',
    packageCount: 1,
    receivableWeightKg: 13,
    agentWeightKg: 12.5,
    latestTracking: '客户退件：不出',
    trackingStaleDays: 2,
    isRemoteArea: false,
    status: 'WAITING_RETURN',
    channelName: 'HKD11',
    agentName: '宇环',
    hasProblemTicket: true
  },
  {
    id: 'SYGJ04021344154',
    createdAt: '2026-04-02 09:23',
    customerName: '1344-TILL',
    customerOrderNo: 'DE-0402',
    systemOrderNo: 'SYGJ04021344154',
    transferNo: '1401428641',
    businessType: 'EXPRESS',
    packageType: 'WPX',
    destinationCountry: '德国',
    carrier: 'DHL',
    packageCount: 1,
    receivableWeightKg: 8,
    agentWeightKg: 7.5,
    latestTracking: '已签收',
    trackingStaleDays: 0,
    isRemoteArea: false,
    status: 'SIGNED',
    channelName: 'HKD01',
    agentName: '宇环',
    hasProblemTicket: false
  },
  {
    id: 'SYGJ06061230001',
    createdAt: '2026-06-06 09:40',
    customerName: '1230-待收货客户',
    customerOrderNo: 'RCV-0606',
    systemOrderNo: 'SYGJ06061230001',
    businessType: 'EXPRESS',
    packageType: 'WPX',
    destinationCountry: '美国',
    carrier: 'DHL',
    packageCount: 2,
    receivableWeightKg: 18,
    agentWeightKg: 18,
    latestTracking: '客户已预报',
    trackingStaleDays: 0,
    isRemoteArea: false,
    status: 'WAITING_RECEIVE',
    channelName: 'DHL HK',
    agentName: '宇环',
    hasProblemTicket: false
  },
  {
    id: 'SYGJ06061230002',
    createdAt: '2026-06-06 09:55',
    customerName: '1230-待发货客户',
    customerOrderNo: 'DSP-0606',
    systemOrderNo: 'SYGJ06061230002',
    businessType: 'EXPRESS',
    packageType: 'WPX',
    destinationCountry: '加拿大',
    carrier: 'UPS',
    packageCount: 1,
    receivableWeightKg: 21,
    agentWeightKg: 19.5,
    latestTracking: '已排货',
    trackingStaleDays: 1,
    isRemoteArea: false,
    status: 'WAITING_DISPATCH',
    channelName: 'UPS 加美线',
    agentName: '加美代理',
    hasProblemTicket: false
  },
  {
    id: 'SYGJ06061230003',
    createdAt: '2026-06-02 14:20',
    customerName: '1230-滞留客户',
    customerOrderNo: 'STUCK-0602',
    systemOrderNo: 'SYGJ06061230003',
    transferNo: 'STK998877',
    businessType: 'EXPRESS',
    packageType: 'WPX',
    destinationCountry: '英国',
    carrier: 'DHL',
    packageCount: 1,
    receivableWeightKg: 32,
    agentWeightKg: 32,
    latestTracking: '清关延误',
    trackingStaleDays: 4,
    isRemoteArea: false,
    status: 'STUCK',
    channelName: 'DHL UK',
    agentName: '英线代理',
    hasProblemTicket: true
  },
  {
    id: 'SYXB0606US001',
    createdAt: '2026-06-06 08:42',
    customerName: 'A100-北美电商',
    customerOrderNo: 'SP-US-0606',
    systemOrderNo: 'SYXB0606US001',
    businessType: 'SMALL_PACKET',
    packageType: 'PAK',
    destinationCountry: '美国',
    carrier: 'USPS',
    packageCount: 8,
    receivableWeightKg: 12.4,
    agentWeightKg: 12,
    latestTracking: '已预报',
    trackingStaleDays: 0,
    isRemoteArea: false,
    status: 'DECLARED',
    channelName: 'USPS 小包线',
    agentName: '蓝玛特',
    hasProblemTicket: false
  },
  {
    id: 'SYXB0606DE002',
    createdAt: '2026-06-06 09:12',
    customerName: 'A100-北美电商',
    customerOrderNo: 'SP-DE-0606',
    systemOrderNo: 'SYXB0606DE002',
    businessType: 'SMALL_PACKET',
    packageType: 'PAK',
    destinationCountry: '德国',
    carrier: 'YANWEN',
    packageCount: 12,
    receivableWeightKg: 6.8,
    agentWeightKg: 6.5,
    latestTracking: '待交邮袋',
    trackingStaleDays: 1,
    isRemoteArea: false,
    status: 'WAITING_DISPATCH',
    channelName: '燕文小包线',
    agentName: '燕文代理',
    hasProblemTicket: false
  },
  {
    id: 'SYXB0606GB003',
    createdAt: '2026-06-06 09:25',
    customerName: 'C318-独立站卖家',
    customerOrderNo: 'SP-GB-0606',
    systemOrderNo: 'SYXB0606GB003',
    transferNo: 'LP00606003GB',
    businessType: 'SMALL_PACKET',
    packageType: 'PAK',
    destinationCountry: '英国',
    carrier: 'ROYALMAIL',
    packageCount: 5,
    receivableWeightKg: 3.2,
    agentWeightKg: 3.2,
    latestTracking: '已交邮袋',
    trackingStaleDays: 0,
    isRemoteArea: false,
    status: 'WAITING_ONLINE',
    channelName: '英国挂号小包',
    agentName: '欧线小包代理',
    hasProblemTicket: false
  },
  {
    id: 'SYXB0605FR004',
    createdAt: '2026-06-05 17:30',
    customerName: 'D502-平台卖家',
    customerOrderNo: 'SP-FR-0605',
    systemOrderNo: 'SYXB0605FR004',
    transferNo: 'LP0605FR004',
    businessType: 'SMALL_PACKET',
    packageType: 'PAK',
    destinationCountry: '法国',
    carrier: 'LA_POSTE',
    packageCount: 3,
    receivableWeightKg: 2.1,
    agentWeightKg: 2,
    latestTracking: '离开处理中心',
    trackingStaleDays: 6,
    isRemoteArea: false,
    status: 'WAITING_ONLINE',
    channelName: '欧邮小包线',
    agentName: '欧邮代理',
    hasProblemTicket: true
  },
  {
    id: 'SYXB0605CA005',
    createdAt: '2026-06-05 14:18',
    customerName: 'E777-加拿大小件',
    customerOrderNo: 'SP-CA-0605',
    systemOrderNo: 'SYXB0605CA005',
    businessType: 'SMALL_PACKET',
    packageType: 'PAK',
    destinationCountry: '加拿大',
    carrier: 'CANADAPOST',
    packageCount: 9,
    receivableWeightKg: 7.6,
    agentWeightKg: 7.4,
    latestTracking: '客户已预报',
    trackingStaleDays: 0,
    isRemoteArea: false,
    status: 'WAITING_RECEIVE',
    channelName: '加拿大轻小件',
    agentName: '加邮代理',
    hasProblemTicket: false
  },
  {
    id: 'SYXB0604AU006',
    createdAt: '2026-06-04 16:05',
    customerName: 'F208-澳洲小包',
    customerOrderNo: 'SP-AU-0604',
    systemOrderNo: 'SYXB0604AU006',
    transferNo: 'LP0604AU006',
    businessType: 'SMALL_PACKET',
    packageType: 'PAK',
    destinationCountry: '澳大利亚',
    carrier: 'AUSPOST',
    packageCount: 4,
    receivableWeightKg: 4.9,
    agentWeightKg: 4.8,
    latestTracking: '妥投',
    trackingStaleDays: 0,
    isRemoteArea: true,
    status: 'SIGNED',
    channelName: '澳邮小包线',
    agentName: '澳邮代理',
    hasProblemTicket: false
  },
  {
    id: 'SYZX0606UK001',
    createdAt: '2026-06-06 09:03',
    customerName: 'B220-FBA 卖家',
    customerOrderNo: 'FBA-UK-0606',
    systemOrderNo: 'SYZX0606UK001',
    businessType: 'DEDICATED_LINE',
    packageType: 'WPX',
    destinationCountry: '英国',
    carrier: '专线',
    packageCount: 16,
    receivableWeightKg: 282,
    agentWeightKg: 282,
    latestTracking: '待排货',
    trackingStaleDays: 0,
    isRemoteArea: false,
    status: 'WAITING_SORT',
    channelName: '英国 FBA 空派',
    agentName: '中飞',
    hasProblemTicket: false
  },
  {
    id: 'SYZX0606US002',
    createdAt: '2026-06-06 10:12',
    customerName: 'B220-FBA 卖家',
    customerOrderNo: 'FBA-US-0606',
    systemOrderNo: 'SYZX0606US002',
    businessType: 'DEDICATED_LINE',
    packageType: 'WPX',
    destinationCountry: '美国',
    carrier: '专线',
    packageCount: 24,
    receivableWeightKg: 418,
    agentWeightKg: 410,
    latestTracking: '已装板',
    trackingStaleDays: 1,
    isRemoteArea: false,
    status: 'WAITING_DISPATCH',
    channelName: '美国 FBA 空派',
    agentName: '美线庄家',
    hasProblemTicket: false
  },
  {
    id: 'SYZX0605CA003',
    createdAt: '2026-06-05 13:45',
    customerName: 'K901-海外仓客户',
    customerOrderNo: 'OW-CA-0605',
    systemOrderNo: 'SYZX0605CA003',
    transferNo: 'ZXCA0605003',
    businessType: 'DEDICATED_LINE',
    packageType: 'WPX',
    destinationCountry: '加拿大',
    carrier: '专线',
    packageCount: 18,
    receivableWeightKg: 356,
    agentWeightKg: 352,
    latestTracking: '航班起飞',
    trackingStaleDays: 2,
    isRemoteArea: false,
    status: 'WAITING_ONLINE',
    channelName: '加拿大海派',
    agentName: '加线庄家',
    hasProblemTicket: false
  },
  {
    id: 'SYZX0604DE004',
    createdAt: '2026-06-04 11:20',
    customerName: 'L610-欧洲大货',
    customerOrderNo: 'EU-DE-0604',
    systemOrderNo: 'SYZX0604DE004',
    transferNo: 'ZXDE0604004',
    businessType: 'DEDICATED_LINE',
    packageType: 'WPX',
    destinationCountry: '德国',
    carrier: '专线',
    packageCount: 32,
    receivableWeightKg: 612,
    agentWeightKg: 608,
    latestTracking: '清关查验',
    trackingStaleDays: 4,
    isRemoteArea: false,
    status: 'PROBLEM',
    channelName: '欧洲卡航',
    agentName: '欧线庄家',
    hasProblemTicket: true
  }
];
