ALTER TABLE "Channel" ADD COLUMN "businessType" TEXT NOT NULL DEFAULT 'EXPRESS';
ALTER TABLE "Channel" ADD COLUMN "category" TEXT NOT NULL DEFAULT 'DHL';
ALTER TABLE "Channel" ADD COLUMN "multiPieceWeightRule" TEXT NOT NULL DEFAULT 'SUM_THEN_COMPARE';
ALTER TABLE "Channel" ADD COLUMN "singleWeightRoundingRule" TEXT NOT NULL DEFAULT 'ACTUAL';
ALTER TABLE "Channel" ADD COLUMN "settlementWeightRule" TEXT NOT NULL DEFAULT 'MAX_ACTUAL_VOLUME';
ALTER TABLE "Channel" ADD COLUMN "settlementWeightRoundingRule" TEXT NOT NULL DEFAULT 'NONE';
ALTER TABLE "Channel" ADD COLUMN "largeCargoThresholdKg" DECIMAL(10,2);
ALTER TABLE "Channel" ADD COLUMN "remoteAreaRule" TEXT NOT NULL DEFAULT 'NONE';
