ALTER TABLE "ReceivableFee"
ADD COLUMN "currency" TEXT NOT NULL DEFAULT 'CNY',
ADD COLUMN "settlementMethod" TEXT,
ADD COLUMN "paymentNo" TEXT,
ADD COLUMN "reconciliationStatus" TEXT NOT NULL DEFAULT 'PENDING',
ADD COLUMN "createdBy" TEXT,
ADD COLUMN "reviewedBy" TEXT,
ADD COLUMN "reviewedAt" TIMESTAMP(3),
ADD COLUMN "remark" TEXT,
ADD COLUMN "voided" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "voidedAt" TIMESTAMP(3),
ADD COLUMN "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
